# INSERT MODE:
# Ctrl+x opens completion list, but it's not listed in help
# WHILE METHOD DESCRIPTION VISIBLE WITH MULTIPLE OVERLOADS:
# Alt+n - next overload
# Alt+p - previous overload

theme = "brc_vs"

[editor]
true-color = true
line-number = "relative"
auto-pairs = false

[editor.cursor-shape]
insert = "bar"
normal = "underline"
select = "underline"

[editor.statusline]
left = ["mode", "spinner", "file-modification-indicator", "file-name", "file-type"]

[editor.lsp]
display-inlay-hints = true
auto-signature-help = false

# [editor.whitespace]
# render = "all"

[editor.whitespace.render]
space = "none"
tab = "all"
nbsp = "none"
nnbsp = "none"
newline = "all"

[editor.indent-guides]
render = true
character = "│"
skip-levels = 1

[editor.inline-diagnostics]
cursor-line = "hint" # error, warning, info, hint

[keys.normal]
j = "move_char_left"
k = "move_visual_line_down"
l = "move_char_right"
i = "move_visual_line_up"
h = "insert_mode"
"ret" = "insert_newline"
"A-down" = ["extend_to_line_bounds", "delete_selection", "paste_after"]
"A-up" = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
"L" = "insert_at_line_end"
"J" = "insert_at_line_start"
"A-d" = "delete_selection"
d = "delete_selection_noyank"
esc = ["collapse_selection", "keep_primary_selection"]
C-q = "goto_word"
C-s = ":write"
C-a = ":write-all"
C-u = "undo"
u = "no_op"
"A-j" = "jump_backward"
"A-l" = "jump_forward"
A-i = "page_up"
A-k = "page_down"
C-j = "goto_first_nonwhitespace"
C-l = "goto_line_end"
"tab" = "no_op"
"H" = "join_selections"
"X" = "increment"
"S-i" = "scroll_up"
"S-k" = "scroll_down"
"C-f" = "search"
"A-f" = "global_search" 
"+" = "increment"
"-" = "decrement"
"C-c" = "yank_to_clipboard"
"C-v" = "paste_clipboard_before"

[keys.normal.g]
s = "goto_line_start"
j = "goto_first_nonwhitespace"

[keys.normal.C-w]
j = "jump_view_left"
k = "jump_view_down"
l = "jump_view_right"
i = "jump_view_up"

[keys.select]
j = "extend_char_left"
k = "extend_visual_line_down"
l = "extend_char_right"
i = "extend_visual_line_up"
d = "delete_selection_noyank"
"C-c" = "yank_to_clipboard"
"C-v" = "paste_clipboard_before"

[keys.select.g]
s = "goto_line_start"
j = "goto_first_nonwhitespace"

[keys.insert]
"tab" = "insert_tab"
C-c = "signature_help"
"A-x" = "normal_mode"
