theme = "brc_vs"

[editor]
true-color = true
line-number = "relative"
auto-pairs = false

[editor.cursor-shape]
insert = "bar"
normal = "underline"
select = "underline"

[editor.lsp]
display-inlay-hints = true

[editor.whitespace]
render = "all"

[editor.indent-guides]
render = true
character = "│"
skip-levels = 1

[editor.inline-diagnostics]
cursor-line = "hint" # error, warning, info, hint

[keys.normal]
j = "move_char_left"
k = "move_visual_line_down"
l = "move_char_right"
i = "move_visual_line_up"
h = "insert_mode"
"A-i" = "page_up"
"A-k" = "page_down"
"ret" = "insert_newline"
"A-down" = ["extend_to_line_bounds", "delete_selection", "paste_after"]
"A-up" = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
"L" = "insert_at_line_end"
"A-d" = "delete_selection"
d = "delete_selection_noyank"
esc = ["collapse_selection", "keep_primary_selection"]
"C-b" = "jump_backward"
"C-i" = "jump_forward"

[keys.normal.g]
s = "goto_line_start"
j = "goto_first_nonwhitespace"

[keys.select]
j = "move_char_left"
k = "move_visual_line_down"
l = "move_char_right"
i = "move_visual_line_up"

[keys.insert]
# Ctrl+x opens completion list, but it's not listed in help
"tab" = "insert_tab"
