[editor]
true-color = true
line-number = "relative"

[editor.cursor-shape]
insert = "bar"
normal = "underline"
select = "underline"

[keys.normal]
j = "move_char_left"
k = "move_visual_line_down"
l = "move_char_right"
i = "move_visual_line_up"
h = "insert_mode"

[keys.select]
j = "move_char_left"
k = "move_visual_line_down"
l = "move_char_right"
i = "move_visual_line_up"
