[[language]]
name = "d"
language-servers = ["serve-d"]
formatter = { command = "dfmt" }
auto-format = true

[[language]]
name = "c-sharp"
indent = { tab-width = 2, unit = "  " }

[language-server.ruff]
command = "ruff"
args = ["server", "--preview", "--verbose"]
config = { settings = { run = "onSave"}}

[[language]]
name = "python"
language-servers = ["pyright", "ruff"]
