inherits = "default"

"ui.background" = { fg = "#FFFFFF", bg = "#2B1D3A"}
"type" = "#4ec9b0"
"type.builtin" = "#4a9cd6"
"type.enum" = "#00ff00"
"string" = "#d69b80"
"comment" = "#588b4e"
"punctuation" = "#ffffff"
"keyword" = "#d8a0df"
"keyword.storage.type" = "#4a9cd6"
"keyword.storage.modifier" = "#4a9cd6"
"function" = "#dcdc9d"
"variable" = "#9cdcf9"
"variable.parameter" = "#9cdcf9"
"operator" = "#b4b4b4"
"constant.numeric" = "#b5cea5"
"constant.builtin" = "#4a9cd6"

"markup.heading" = "#11FFAA"
"markup.heading.2" = "#FF1144"
